import type { Metadata } from 'next'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import './globals.css'
import { AuthProvider } from '@/contexts/AuthContext'
import { LocalizationProvider } from '@/contexts/LocalizationContext'
import { BreedProvider } from '@/contexts/BreedContext'
import { PersonalityProvider } from '@/contexts/PersonalityContext'
import { PostProvider } from '@/contexts/PostContext'

export const metadata: Metadata = {
  title: 'Bichos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  

  return (
    <html lang="pt-br">
      <body className="overlay-x-hidden font-jakarta">
        <AuthProvider>
          <LocalizationProvider>
            <BreedProvider>
              <PersonalityProvider>
                <PostProvider>
                  <>
                    <Navbar />
                    {children}
                    {/* <Footer /> */}
                  </>
                </PostProvider>
              </PersonalityProvider>
            </BreedProvider>
          </LocalizationProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
